name: Generate PDF Manual

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Convert Markdown to PDF
      uses: baileyjm02/markdown-to-pdf@v1
      with:
        input_path: docs/manual.md
        output_dir: docs/
        images_dir: docs/
        build_html: false
        
    - name: Commit and push PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/manual.pdf
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generate PDF manual [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: user-manual-pdf
        path: docs/manual.pdf
        retention-days: 30
